### ISSUE TITLE
kubectl rollout and status fonction on cronjob

### ISSUE THREAD

**Issue by heurtematte** [EclipseFdn/jenkins-pipeline-shared#5]
Method `rollout` and `status` should be avoid while performing on a cronjob
https://github.com/EclipseFdn/jenkins-pipeline-shared/blob/8d3c89443783cf42b3d3bc1f5806b37a02c06449/vars/updateContainerImage.groovy#L34

```groovy
 if ! kubectl rollout status "${effectiveConfig.kind}/\${firstResourceName}" -n '${effectiveConfig.namespace}'; then
          # will fail if rollout does not succeed in less than .spec.progressDeadlineSeconds
          kubectl rollout undo "${effectiveConfig.kind}/\${firstResourceName}" -n '${effectiveConfig.namespace}'
          exit 1
        fi
```

see reference: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/28130

**Comment by autumnfound** [comment]
It looks like an alternative is to configure the missing mechanisms for the cronjob that are missing. Its odd that this used to work fine and is broken now, is there maybe some configs that were accidentally dropped in the cluster for this?

**Comment by mbarbero** [comment]
AFAICT, nothing changed on the cluster side, but the kubectl binary (i.e. the client) may be refusing this after an upgrade.
